name: macOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use Node 18 (LTS); node 22 may not be supported by all tools

      - name: Install dependencies
        run: npm install

      - name: Build frontend (if any)
        run: npm run build

      - name: List current directory (debug)
        run: ls -al

      - name: Package macOS app (no publish)
        run: npm run dist
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: List dist contents (debug)
        run: ls -R dist

      - name: Upload .dmg file
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist/**/**/*.dmg  # broader path in case it's not in dist/mac
